[package]
name = "vid-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
headless_chrome = "1.0.15"
m3u8-rs = "6.0.0"
reqwest = { version = "0.12.9", features = ["blocking"] }
tokio = { version = "1.41.0", features = ["full"] }
